# Имя флоу
name: test deploy dockerfile

# Когда действие запустится (триггеры)
on:
  push:
    # при push в master
    branches: [ main ]

  # pull_request:
  #   # при создании pull request на master
  #   branches: [ master ]

# Что будем делать (экшены)
jobs:
  # Имя действия, придумываем сами
  deploy-dockerfile:
  
    build:
      environment: production
      env:
        BOX_PASSWORD: ${{ secrets.BOX_PASSWORD }}

      # На какой ОС будет работать виртуальная машина
      # Можно выбрать Ubuntu, Windows Server или macOS
      runs-on: ubuntu-latest
      # Шаги действия
      steps:

        # Шаг 1: собираем сервисы в режиме тестирования
        - uses: actions/checkout@v2
        
        - name: Show secret              
          run: |
              echo $BOX_PASSWORD is total secret  
   

      # - name: Docker build
      #   run: docker build -f Dockerfile -t deploy --build-arg ZIP_ACCESS_TOKE=123 .
 
      # # Шаг 2: 
      # - name: Docker ps
      #   run: docker images

      # # Шаг 3: 
      # - name: Docker run
      #   run: docker run deploy pwd

      # # Шаг 4: 
      # - name: Docker ps
      #   run: docker ps -a

      # # # Шаг 3: запускаем тесты с небольшой детализацией
      # # - name: Run tests
      # #   run: dotnet test LOT.Tests --verbosity normal