name: learn-triggers
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    # runs-on: ubuntu-latest
    steps:
      - run: echo 'building'
      - run: pwd

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo 'publishing'
      - run: pwd
